version: '2'

services:
  teamcity:
    image: jetbrains/teamcity-server:latest
    volumes:
      - ./target/:/data/teamcity_server/datadir/plugins/
    ports:
      - "8080:8111"

  teamcity_agent:
    image: jetbrains/teamcity-agent:latest
    depends_on:
      - teamcity
    links:
      - teamcity:teamcity
    environment:
      - SERVER_URL=teamcity:8111
      - AGENT_NAME="tcagent_docker"
