name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: tc-discord-webhooks.zip
          path: target/tc-discord-webhooks.zip
      - name: Upload jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: tc-discord-webhooks-server/target/site
      - name: Upload surefire report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: tc-discord-webhooks-server/target/surefire-reports
