name: Close stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue did not have any activity in the last 60 days. It has been marked as stale and will be closed soon.'
          stale-pr-message: 'This pull request did not have any activity in the last 60 days. It has been marked as stale and will be closed soon.'
          stale-issue-label: 'stale - no activity'
          stale-pr-label: 'stale - no activity'
          exempt-issue-labels: 'in progress'
          exempt-pr-labels: 'in progress'
          days-before-stale: 60
          days-before-close: 7